//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Threads = new HashSet<Thread>();
        }

        [Display(Name = "Username")]
        [StringLength(25)]
        public string username { get; set; }

        [MaxLength(20, ErrorMessage = "The password cannot exceed 20 characters. "),
         MinLength(5, ErrorMessage = "The password must have at least 5 characters. ")]
        [Required(ErrorMessage = "Please enter a password.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Required(ErrorMessage = "Please enter a first name.")]
        [Display(Name = "First Name")]
        [StringLength(50)]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Please enter a last name.")]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Please enter an email.")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [StringLength(50)]
        public string email { get; set; }

        [Display(Name = "Image Path")]
        [DataType(DataType.ImageUrl)]
        [StringLength(250)]
        public string image_path { get; set; }

        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Please enter interests.")]
        [Display(Name = "Interests")]
        [StringLength(3000)]
        public string interests { get; set; }

        [Required(ErrorMessage = "Please enter a favourite quote.")]
        [Display(Name = "Favourite Quote")]
        [StringLength(1000)]
        public string favourite_quote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
